{-# language PatternSynonyms #-}

--Notice: Generated by scripts/Generate.hs
--This module is generated. Do not modify its contents by hand.
module Fortios.Generated
  ( pattern H_action
  , pattern H_app
  , pattern H_appcat
  , pattern H_appid
  , pattern H_applist
  , pattern H_apprisk
  , pattern H_cat
  , pattern H_catdesc
  , pattern H_countweb
  , pattern H_craction
  , pattern H_crlevel
  , pattern H_crscore
  , pattern H_date
  , pattern H_devid
  , pattern H_devname
  , pattern H_dhcp_msg
  , pattern H_direction
  , pattern H_dstcountry
  , pattern H_dstinetsvc
  , pattern H_dstintf
  , pattern H_dstintfrole
  , pattern H_dstip
  , pattern H_dstport
  , pattern H_duration
  , pattern H_error
  , pattern H_eventtime
  , pattern H_eventtype
  , pattern H_hostname
  , pattern H_interface
  , pattern H_ip
  , pattern H_lanin
  , pattern H_lanout
  , pattern H_lease
  , pattern H_level
  , pattern H_logdesc
  , pattern H_logid
  , pattern H_mac
  , pattern H_mastersrcmac
  , pattern H_method
  , pattern H_msg
  , pattern H_osname
  , pattern H_policyid
  , pattern H_policytype
  , pattern H_poluuid
  , pattern H_profile
  , pattern H_proto
  , pattern H_rcvdbyte
  , pattern H_rcvddelta
  , pattern H_rcvdpkt
  , pattern H_referralurl
  , pattern H_reqtype
  , pattern H_sentbyte
  , pattern H_sentdelta
  , pattern H_sentpkt
  , pattern H_service
  , pattern H_sessionid
  , pattern H_srccountry
  , pattern H_srchwvendor
  , pattern H_srcintf
  , pattern H_srcintfrole
  , pattern H_srcip
  , pattern H_srcmac
  , pattern H_srcname
  , pattern H_srcport
  , pattern H_srcserver
  , pattern H_srcswversion
  , pattern H_subtype
  , pattern H_time
  , pattern H_trandisp
  , pattern H_type
  , pattern H_tz
  , pattern H_url
  , pattern H_user
  , pattern H_utmaction
  , pattern H_vd
  , pattern H_vwlid
  , pattern H_wanin
  , pattern H_wanout

  , hashString2
  , hashString3
  , hashString4
  , hashString5
  , hashString6
  , hashString7
  , hashString8
  , hashString9
  , hashString10
  , hashString11
  , hashString12

  ) where

import Fortios.Hash (duohash,quadrohash)
import Data.Bytes.Types (Bytes(Bytes))

import Data.Primitive (ByteArray)

pattern H_action :: Word
pattern H_action = 6

pattern H_app :: Word
pattern H_app = 3

pattern H_appcat :: Word
pattern H_appcat = 1

pattern H_appid :: Word
pattern H_appid = 21

pattern H_applist :: Word
pattern H_applist = 19

pattern H_apprisk :: Word
pattern H_apprisk = 25

pattern H_cat :: Word
pattern H_cat = 4

pattern H_catdesc :: Word
pattern H_catdesc = 13

pattern H_countweb :: Word
pattern H_countweb = 3

pattern H_craction :: Word
pattern H_craction = 8

pattern H_crlevel :: Word
pattern H_crlevel = 18

pattern H_crscore :: Word
pattern H_crscore = 12

pattern H_date :: Word
pattern H_date = 0

pattern H_devid :: Word
pattern H_devid = 14

pattern H_devname :: Word
pattern H_devname = 22

pattern H_dhcp_msg :: Word
pattern H_dhcp_msg = 2

pattern H_direction :: Word
pattern H_direction = 2

pattern H_dstcountry :: Word
pattern H_dstcountry = 1

pattern H_dstinetsvc :: Word
pattern H_dstinetsvc = 3

pattern H_dstintf :: Word
pattern H_dstintf = 1

pattern H_dstintfrole :: Word
pattern H_dstintfrole = 3

pattern H_dstip :: Word
pattern H_dstip = 4

pattern H_dstport :: Word
pattern H_dstport = 8

pattern H_duration :: Word
pattern H_duration = 5

pattern H_error :: Word
pattern H_error = 9

pattern H_eventtime :: Word
pattern H_eventtime = 1

pattern H_eventtype :: Word
pattern H_eventtype = 5

pattern H_hostname :: Word
pattern H_hostname = 9

pattern H_interface :: Word
pattern H_interface = 0

pattern H_ip :: Word
pattern H_ip = 1

pattern H_lanin :: Word
pattern H_lanin = 2

pattern H_lanout :: Word
pattern H_lanout = 2

pattern H_lease :: Word
pattern H_lease = 10

pattern H_level :: Word
pattern H_level = 18

pattern H_logdesc :: Word
pattern H_logdesc = 16

pattern H_logid :: Word
pattern H_logid = 6

pattern H_mac :: Word
pattern H_mac = 2

pattern H_mastersrcmac :: Word
pattern H_mastersrcmac = 1

pattern H_method :: Word
pattern H_method = 3

pattern H_msg :: Word
pattern H_msg = 0

pattern H_osname :: Word
pattern H_osname = 7

pattern H_policyid :: Word
pattern H_policyid = 6

pattern H_policytype :: Word
pattern H_policytype = 0

pattern H_poluuid :: Word
pattern H_poluuid = 17

pattern H_profile :: Word
pattern H_profile = 26

pattern H_proto :: Word
pattern H_proto = 8

pattern H_rcvdbyte :: Word
pattern H_rcvdbyte = 7

pattern H_rcvddelta :: Word
pattern H_rcvddelta = 8

pattern H_rcvdpkt :: Word
pattern H_rcvdpkt = 6

pattern H_referralurl :: Word
pattern H_referralurl = 0

pattern H_reqtype :: Word
pattern H_reqtype = 10

pattern H_sentbyte :: Word
pattern H_sentbyte = 4

pattern H_sentdelta :: Word
pattern H_sentdelta = 11

pattern H_sentpkt :: Word
pattern H_sentpkt = 5

pattern H_service :: Word
pattern H_service = 23

pattern H_sessionid :: Word
pattern H_sessionid = 7

pattern H_srccountry :: Word
pattern H_srccountry = 2

pattern H_srchwvendor :: Word
pattern H_srchwvendor = 2

pattern H_srcintf :: Word
pattern H_srcintf = 2

pattern H_srcintfrole :: Word
pattern H_srcintfrole = 1

pattern H_srcip :: Word
pattern H_srcip = 13

pattern H_srcmac :: Word
pattern H_srcmac = 4

pattern H_srcname :: Word
pattern H_srcname = 7

pattern H_srcport :: Word
pattern H_srcport = 9

pattern H_srcserver :: Word
pattern H_srcserver = 3

pattern H_srcswversion :: Word
pattern H_srcswversion = 0

pattern H_subtype :: Word
pattern H_subtype = 21

pattern H_time :: Word
pattern H_time = 3

pattern H_trandisp :: Word
pattern H_trandisp = 0

pattern H_type :: Word
pattern H_type = 4

pattern H_tz :: Word
pattern H_tz = 0

pattern H_url :: Word
pattern H_url = 5

pattern H_user :: Word
pattern H_user = 2

pattern H_utmaction :: Word
pattern H_utmaction = 10

pattern H_vd :: Word
pattern H_vd = 2

pattern H_vwlid :: Word
pattern H_vwlid = 20

pattern H_wanin :: Word
pattern H_wanin = 16

pattern H_wanout :: Word
pattern H_wanout = 0


hashString2 :: ByteArray -> Int -> Word
hashString2 arr off = rem (duohash 0 53285 16798 (Bytes arr off 2)) 4

hashString3 :: ByteArray -> Int -> Word
hashString3 arr off = rem (duohash 0 62987 7739 (Bytes arr off 2)) 8

hashString4 :: ByteArray -> Int -> Word
hashString4 arr off = rem (duohash 0 34915 60732 (Bytes arr off 4)) 8

hashString5 :: ByteArray -> Int -> Word
hashString5 arr off = rem (duohash 0 15274 40003 (Bytes arr off 4)) 32

hashString6 :: ByteArray -> Int -> Word
hashString6 arr off = rem (duohash 0 30754 52771 (Bytes arr off 6)) 8

hashString7 :: ByteArray -> Int -> Word
hashString7 arr off = rem (quadrohash 0 28583 4580 38468 44705 (Bytes arr off 4)) 32

hashString8 :: ByteArray -> Int -> Word
hashString8 arr off = rem (quadrohash 0 17913 60490 23788 9227 (Bytes arr off 8)) 16

hashString9 :: ByteArray -> Int -> Word
hashString9 arr off = rem (duohash 0 30451 42396 (Bytes arr off 8)) 16

hashString10 :: ByteArray -> Int -> Word
hashString10 arr off = rem (duohash 0 23475 24937 (Bytes arr off 10)) 4

hashString11 :: ByteArray -> Int -> Word
hashString11 arr off = rem (duohash 0 33429 58164 (Bytes arr off 10)) 4

hashString12 :: ByteArray -> Int -> Word
hashString12 arr off = rem (duohash 0 27549 47425 (Bytes arr off 12)) 2


